
### Import a bot
POST http://localhost:3000/manage/welcome-bot/import
Content-Type: application/tar+gzip

< ./bots/welcome_bot.tgz

### Delete bot
POST http://localhost:3000/manage/welcome-bot/delete
Content-Type: application/json

{
  "type": "text",
  "text": "text"
}



### Converse
POST http://localhost:3000/converse/welcome/sendMessage/hello
Content-Type: application/json

{
  "type": "text",
  "text": "text"
}
