
### Import a bot
POST http://localhost:3000/manage/welcome_bot/import
X-Api-Key: abc123
Content-Type: application/tar+gzip

< ./bots/welcome_bot.tgz

### Delete bot
POST http://localhost:3000/manage/welcome_bot/delete
X-Api-Key: abc123
Content-Type: application/json

{
  "type": "text",
  "text": "text"
}

