blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://forum.botpress.com/
    about: If you have a "How do I?" question please ask in the forum https://forum.botpress.com
